# Generated by Django 4.1.10 on 2023-08-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateTrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_name', models.CharField(max_length=50)),
                ('guard_mobile_number', models.CharField(max_length=10)),
                ('guard_aadhar', models.CharField(max_length=12, null=True, unique=True)),
                ('traffic_description', models.CharField(max_length=50)),
                ('person_allowed_name', models.CharField(max_length=50)),
                ('person_allowed_number', models.CharField(max_length=10)),
                ('person_allowed_adhar', models.CharField(max_length=12, null=True, unique=True)),
                ('family_head_name', models.CharField(max_length=50)),
                ('family_head_number', models.CharField(max_length=10)),
                ('family_head_adhar', models.CharField(max_length=12, null=True, unique=True)),
                ('complete_address', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GateTrafficLog',
                'managed': False,
            },
        ),
    ]
