# Generated by Django 4.2.3 on 2023-08-01 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_manipulation', '0003_myuserheadaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='aadhar_number',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='HeadMemberRealtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_head', models.CharField(max_length=10)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to=settings.AUTH_USER_MODEL, to_field='mobile_number')),
            ],
            options={
                'db_table': 'FamilyRelation',
            },
        ),
    ]
